inital commit
Jeremiahiro/profile_card pull request #3
Opened 2023-02-03 14:17 UTC by sabioyo

2023-02-04 20:34 UTC, Jeremiahiro requested changes
<img width="1435" alt="Screenshot 2023-02-04 at 21 33 23" src="https://user-images.githubusercontent.com/34809759/216788517-c7cf615c-9a21-4c61-94d7-ccc023d32422.png">

- No social icon
- too much use of margin
-  wrong combination and use of flex and grid property

2023-02-04 20:34 UTC, Jeremiahiro commented on sabi/styles.css
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
You need two columns, why are you splitting template-columns into four?

2023-02-04 20:34 UTC, Jeremiahiro commented on sabi/styles.css
> +    display:flexbox;
flexbox is not a flex property

2023-02-04 20:34 UTC, Jeremiahiro commented on sabi/styles.css
> +    align-items: flex-start;
flex and grid do not go together

2023-02-08 04:47 UTC, Jeremiahiro commented
Well done but you are not there yet. You missed a few closing div tags and a few divs that are not necessary. The issues raised in the previous review have also not been addressed.

2023-02-08 14:13 UTC, sabioyo commented
changes have been made.

2023-02-11 20:08 UTC, merged